package com.health_insurance.phm_cases;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Member")
public class Member implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Member ID")
	private java.lang.String id;

	public Member() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public Member(java.lang.String id) {
		this.id = id;
	}

}