package com.health_insurance.phm_cases;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.kie.api.definition.type.Description;
import org.kie.api.definition.type.Label;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("Reminder Notification")
@Description("Reminder to be sent if task not soft completed by given period of time.")
public class Reminder implements Serializable {

    private static final long serialVersionUID = 9203552419795952130L;

    @Label("eMail Address")
    @Description("Address where to send the reminder message.")
    private String address;
    @Label("Subject")
    @Description("Subject of the reminder message.")
    private String subject;
    @Label("Body")
    @Description("Text of the reminder.")
    private String body;
    @Label("Sender eMail address")
    @Description("Sender address of the reminder message.")
    private String from;

    /**
     * Reminder to be sent if task not soft completed by given period of time.
     */
    public Reminder() {
    }

    /**
     * Return the address where to send the reminder message.
     *
     * @return the address
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Set the address where to send the reminder message.
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Return the subject of the reminder message.
     *
     * @return the subject of the message
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Set the subject of the reminder message.
     *
     * @param subject
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Return the text of the reminder.
     *
     * @return the body of the message
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Set the text of the reminder.
     *
     * @param body
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Return the sender address of the reminder message.
     *
     * @return the sender address
     */
    public String getFrom() {
        return this.from;
    }

    /**
     * Set the sender address of the reminder message.
     *
     * @param from
     */
    public void setFrom(String from) {
        this.from = from;
    }

    /**
     * The object as a JSON string.
     *
     * @return the object as a JSON string
     */
    @Override
    public String toString() {
        final ObjectMapper objectMapper = new ObjectMapper();
        try {
            objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
            return objectMapper.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
        return "";
    }

    /**
     * Reminder to be sent if task not soft completed by given period of time.
     *
     * @param address
     * @param subject
     * @param body
     * @param from
     */
    public Reminder(String address, String subject,
                    String body, String from) {
        this.address = address;
        this.subject = subject;
        this.body = body;
        this.from = from;
    }

}