package com.health_insurance.phm_cases;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.kie.api.definition.type.Description;
import org.kie.api.definition.type.Label;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */
@Label(value = "Task Actor Assignment")
@Description(value = "Properties of a task actor assignment.")
public class TaskActorAssignment implements Serializable {

	private static final long serialVersionUID = 3058923314416600036L;

	@Label(value = "Actor")
	@Description(value = "The actor of the task.")
	private String actor;
	@Label(value = "Channel")
	@Description(value = "The name of the application where the task is performed.")
	private String channel;
	@Label(value = "Escalation Actor")
	@Description(value = "The actor of the escalation.")
	private String escalationActor;
	@Label(value = "EscalationChannel")
	@Description(value = "The application where the escalation is performed.")
	private String escalationChannel;

	/**
	 * Properties of a task actor assignment.
	 */
	public TaskActorAssignment() {
	}

	/**
	 * Return the actor of the task.
	 *
	 * @return the task actor
	 */
	public String getActor() {
		return this.actor;
	}

	/**
	 * Set the actor of the task.
	 *
	 * @param actor
	 */
	public void setActor(String actor) {
		this.actor = actor;
	}

	/**
	 * Return the name of the application where the task is performed.
	 *
	 * @return the task application name
	 */
	public String getChannel() {
		return this.channel;
	}

	/**
	 * Set the name of the application where the task is performed.
	 *
	 * @param channel
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * Return the actor of the escalation.
	 *
	 * @return the escalation actor
	 */
	public String getEscalationActor() {
		return this.escalationActor;
	}

	/**
	 * Set the actor of the escalation.
	 *
	 * @param escalationActor
	 */
	public void setEscalationActor(String escalationActor) {
		this.escalationActor = escalationActor;
	}

	/**
	 * Return the name of the application where the escalation is performed.
	 *
	 * @return the escalation application name
	 */
	public String getEscalationChannel() {
		return this.escalationChannel;
	}

	/**
	 * Set the name of the application where the escalation is performed.
	 *
	 * @param escalationChannel
	 */
	public void setEscalationChannel(String escalationChannel) {
		this.escalationChannel = escalationChannel;
	}

	/**
	 * The object as a JSON string.
	 *
	 * @return the object as a JSON string
	 */

	@Override
	public String toString() {
		final ObjectMapper objectMapper = new ObjectMapper();
		try {
			objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
			return objectMapper.writeValueAsString(this);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}
		return "";
	}

	/**
	 * Properties of a task actor assignment.
	 *
	 * @param actor
	 * @param channel
	 * @param escalationActor
	 * @param escalationChannel
	 */
	public TaskActorAssignment(String actor,
			String channel, String escalationActor,
			String escalationChannel) {
		this.actor = actor;
		this.channel = channel;
		this.escalationActor = escalationActor;
		this.escalationChannel = escalationChannel;
	}

}