package com.health_insurance.phm_cases;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Trigger implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Trigger() {
    }




}