package com.health_insurance.phm_cases;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Trigger")
public class Trigger implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Original Trigger ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Trigger Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Domain")
	private java.lang.String domain;

	@org.kie.api.definition.type.Label(value = "Member")
	private com.health_insurance.phm_cases.Member member;

	public Trigger() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getDomain() {
		return this.domain;
	}

	public void setDomain(java.lang.String domain) {
		this.domain = domain;
	}

	public com.health_insurance.phm_cases.Member getMember() {
		return this.member;
	}

	public void setMember(com.health_insurance.phm_cases.Member member) {
		this.member = member;
	}

	public Trigger(java.lang.String id, java.lang.String description,
			java.lang.String domain,
			com.health_insurance.phm_cases.Member member) {
		this.id = id;
		this.description = description;
		this.domain = domain;
		this.member = member;
	}

}